INSERT INTO ESTADO (NOME,IBGE) VALUES ('AMAZONAS','13');
INSERT INTO ESTADO (NOME,IBGE) VALUES ('PARA','15');

INSERT INTO CIDADE (NOME,IBGE,ESTADO_ID) VALUES ('MANAUS','1302603',1);
INSERT INTO CIDADE (NOME,IBGE,ESTADO_ID) VALUES ('IRANDUBA','1301852',1);
INSERT INTO CIDADE (NOME,IBGE,ESTADO_ID) VALUES ('BELEM','1501402',2);

